name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main  # This triggers the workflow when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # This triggers the workflow for pull requests targeting the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
